plugins {
    id 'multiloader-common'
    id 'com.modrinth.minotaur'
    id 'net.darkhax.curseforgegradle'
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(':common')) {
        capabilities {
            requireCapability "$group:$mod_id"
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

afterEvaluate {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = modrinth_id
        versionName = mod_id[0].toUpperCase() + mod_id.substring(1) + " " + version
        versionNumber = version
        versionType = "release"
        uploadFile = project.name == "fabric" ? tasks.named("remapJar") : tasks.named("jar")
        gameVersions = [minecraft_version]
        loaders = [project.name]
        if(project.name == "fabric") {
            dependencies {
                required.project "fabric-api"
            }
        }
    }
}
