plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.11-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.115' apply false
    // see https://github.com/modrinth/minotaur for new versions
    id 'com.modrinth.minotaur' version "2.+" apply false
    // see https://github.com/henkelmax/curse-gradle/releases for new versions
    id 'de.maxhenkel.cursegradle' version "1.5.1" apply false
}
